language: php
php:
  - 5.6
sudo: false
branches:
  only:
    - master
script:
  - rbenv local 2.4 ; gem install tw
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./site deploy'
cache:
  directories:
    - .vendor
