language: php
php:
  - 5.6
sudo: false
branches:
  only:
    - master
before_script:
  - npm install -g bower
script:
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./site deploy'
cache:
  directories:
    - .vendor
    - source/assets
