services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.pcre:
        class: Jasny\Twig\PcreExtension
        tags:
            - { name: twig.extension }
#    sharkpp.extension.debug2:
#        class: Sharkpp\Twig\Extensions\Debug2
#        tags:
#            - { name: twig.extension }
