sculpin_pagination:
    max_per_page: 20

sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename.html
    statics:
        type: path
        path: _statics
        singular_name: static
        layout: default
        enabled: true
        taxonomies:
            - tags
            - categories

icelus:
    prefix: '/thumbs'
#   output_dir:

