sculpin_pagination:
    max_per_page: 20

sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
    hsp:
        type: path
        path: _posts
        permalink: blog2/:year/
        layout: project
