name: build

on:
  push:
    branches:
    - master

jobs:
  build-deploy:

    runs-on: ubuntu-22.04
    steps:

    - name: Setup PHP 7.4
      run:
        sudo env LC_ALL=C.UTF-8 add-apt-repository --yes ppa:ondrej/php &&
        sudo apt-get install php7.4-fpm php7.4-common php7.4-dev php7.4-curl php7.4-gd php7.4-json php7.4-mysql php7.4-odbc php7.4-pgsql php7.4-pspell php7.4-readline php7.4-sqlite3 php7.4-tidy php7.4-xml php7.4-xmlrpc php7.4-bcmath php7.4-bz2 php7.4-intl php7.4-mbstring php7.4-phpdbg php7.4-soap php7.4-zip php-imagick php-redis php-memcached &&
        sudo ls -l /usr/bin/php* &&
        sudo update-alternatives --set php /usr/bin/php7.4

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.16'

    - name: install bower
      run: npm install -g bower

    - name: Checkout master
      uses: actions/checkout@master

    - name: Cache composer packages
      uses: actions/cache@v3
      id: composer-cache
      with:
        path: |
          .vendor
        key: ${{ runner.OS }}-composer-cache-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.OS }}-composer-cache-

    - name: Cache bower packages
      uses: actions/cache@v3
      id: bower-cache
      with:
        path: |
          .bower
          source/assets
        key: ${{ runner.OS }}-bower-cache-${{ hashFiles('**/.bower.json') }}
        restore-keys: |
          ${{ runner.OS }}-bower-cache-

    - name: composer install
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: php ./composer.phar install

    - name: bower install
      if: steps.bower-cache.outputs.cache-hit != 'true'
      #run: php .vendor/beelab/bowerphp/bin/bowerphp install
      run: bower install

    - name: Build
      run: ./site deploy
      env:
        GOOGLE_ANALYTICS_TRACKING_ID: UA-5908801-2
        REPO_SLUG: sharkpp/www.sharkpp.net

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./output_prod
